public class MockHttpResponse implements HttpCalloutMock {
	private Integer statusCode;
	private String body;

	public MockHttpResponse(Integer statusCode, String body) {
		this.statusCode = statusCode;
		this.body       = body;
	}

	public HttpResponse respond(HttpRequest req) {
		HttpResponse res = new HttpResponse();
		res.setStatusCode(this.statusCode);
		res.setBody(this.body);
		res.setStatus('OK');
		return res;
	}
}
